### ISSUE TITLE
E364 when using base libcursor.dll on 64-bit Vim

### ISSUE THREAD

**Issue by meshkinyar** [gustaphe/winterm.vim#1]
I apologize if this isn't proper etiquette, but I'd like to mention this issue to others who may have it. After installing the plugin, Vim returns E364 on startup when using the installed libcursor.dll. My guess is that this occurs because I am running a 64-bit distribution of Vim, but I have little experience with C so I honestly have no clue.

I was able to fix the error by simply compiling the included libcursor.c file into a new .dll, allowing the plugin to work as intended.

**Comment by gustaphe** [comment]
No, you're doing it right.

I haven't quite had opportunity to check this properly, but apparently the goal of this package is sorted natively as of quite short after this package was created:

https://github.com/vim/vim/commit/df5320c439e9a7f7bf1ebff3cb455d45e223547a

**Comment by meshkinyar** [comment]
Huh. I'm surprised I didn't see this mentioned in other Windows Terminal threads. Certainly a major step for wt + vim compatibility. Anyway, cheers! :)
